<a href="https://colab.research.google.com/github/Sauvi72/Data_sci_Python/blob/main/lec_04_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np


In [8]:
import numpy as np

a = np.array([1,3,5,0,'2', False])
print(bool(a[-1]))
a = False
print(bool(a))


True
False


In [13]:
a = '10'
print(bool(a))

True


In [17]:
a = np.zeros([2,4])
print(a)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
a = np.zeros([2,4,2])
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [27]:
import numpy as np

a = np.ones((4,4), dtype=int)

print(a)
print(type(a[0][0]))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
<class 'numpy.int64'>


In [32]:
import numpy as np

a = np.empty((4,5), dtype=int)
print(a)

[[                  0                   0 4599075939470750515
  4607182418800017408                   0]
 [                  0 4607182418800017408 4607182418800017408
  4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408
                    0                   0]
 [4607182418800017408 4602678819172646912                   0
                    0 4607182418800017408]]


In [34]:
a = np.full(4,5,dtype = int)
print(a)

[5 5 5 5]


In [45]:
a = np.arange(-3,4)         #  array.arange(start value , end value)
print(a)

[-3 -2 -1  0  1  2  3]


In [47]:
a = np.arange(3)
print(a)

[0 1 2]


In [44]:
#linspace() -----------------> print equal no. b/w two given no .

#linspace( start, end , no. of values)
# --------------- * ---- * ---- * --------------------------------

a = np.linspace(1,4,4)
print(a)

[1. 2. 3. 4.]


In [50]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])

print(a.shape)
print(a.size)

(2, 3)
6


In [49]:
#shape , size
a = np.array([10,20,30,40])

print(a.shape)
print(a.size)

(4,)
4


In [83]:
# np.random.randint(low, high) ------------> pick random values

a = np.random.randint(0,4)
print(a)

0


In [67]:
# np.random.choice() ----------> choose value from a given array

#np.random.choice(a, size=None, replace=True, p=None)

a = np.random.choice([8,7,6] , [4,2])
print(a)

[[8 6]
 [8 8]
 [8 8]
 [6 8]]


In [ ]:
# List       -> []
# Tuple      -> ()
# Dictionary -> {}
# Set        -> {}
# NumPy Array -> np.array([])

In [ ]:
#broadcast



In [93]:


a = np.array([2,3,4,5,6])
b = (2,3,4,5,6)

print(a * 2)
print(a+b)
print(2+a)
print(a/b)
print(a-b-1)




[ 4  6  8 10 12]
[ 4  6  8 10 12]
[4 5 6 7 8]
[1. 1. 1. 1. 1.]
[-1 -1 -1 -1 -1]


In [96]:


a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])

print(a * 2)
print(a + b)
print(2 + a)
print(a / b)
print(a - b - 1)

[ 2  4  6  8 10]
[ 3  5  7  9 11]
[3 4 5 6 7]
[0.5        0.66666667 0.75       0.8        0.83333333]
[-2 -2 -2 -2 -2]


In [103]:


a = np.random.randint(2, 5, 4)
print(a)



[2 2 3 3]


In [104]:

a = np.random.randint(2, 5, 6)
print(a)

b = a.reshape(2, 3)
print(b)

[3 4 3 3 2 4]
[[3 4 3]
 [3 2 4]]


In [105]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)

b = a.transpose()      # transpose
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [115]:
a = np.array([[1, 2],
              [3, 4],
              [3,6]])

b = np.array([[5, 6],
              [7, 8],
              [3,6]])

c = np.concatenate((a, b), axis= 0)
d = np.concatenate((a, b), axis= 1)

print(c)
print(" ")
print(d)

[[1 2]
 [3 4]
 [3 6]
 [5 6]
 [7 8]
 [3 6]]
 
[[1 2 5 6]
 [3 4 7 8]
 [3 6 3 6]]


In [119]:
a = np.array([[3, 1, 2],
              [9, 5, 7]])
#sort()

print(np.sort(a))

[[1 2 3]
 [5 7 9]]


In [120]:
#sort()
a = np.array([5, 2, 8, 1, 4])

print(np.sort(a))

[1 2 4 5 8]


In [128]:
a = np.array([[3, 5, 11],
              [9, 15, 7]])

print(np.sort(a, axis=0))           #sort column-wise (each)

[[ 3  5  7]
 [ 9 15 11]]


In [130]:
# WHERE ()

a = np.random.randint(2,15,6)
b = np.random.randint(1,19,6)

c = np.where(b>2, b, a)
print(c)


[17  4 17  5  4 18]


In [134]:
a = np.array([[3, 5, 11],
              [9, 15, 7]])

b = np.array([[1, 35, 11],
              [9, 75, 91]])

print(np.sort(a, axis=0))
print(" - ")
c = np.where(b>2, b, a)
print(c)

[[ 3  5  7]
 [ 9 15 11]]
 - 
[[ 3 35 11]
 [ 9 75 91]]


In [135]:
a = np.array([[3, 5, 11],
              [9, 15, 7]])

b = np.array([[1, 35, 11],
              [9, 75, 91]])

c = np.where(b>2, b, a)
print(c)

[[ 3 35 11]
 [ 9 75 91]]


In [136]:
a = np.array([10, 20, 30, 40, 50])

print("Array =", a)

print("Sum  =", np.sum(a))
print("Mean =", np.mean(a))
print("Std  =", np.std(a))
print("Min  =", np.min(a))

Array = [10 20 30 40 50]
Sum  = 150
Mean = 30.0
Std  = 14.142135623730951
Min  = 10


In [138]:
a = np.random.randint(1, 20, 6)

print("Array =", a)
print("Sum   =", np.sum(a))
print("Mean  =", np.mean(a))
print("Std   =", np.std(a))
print("Min   =", np.min(a))

Array = [ 3 10 15  9 12 15]
Sum   = 64
Mean  = 10.666666666666666
Std   = 4.109609335312651
Min   = 3


In [140]:

a = np.array([12, 5, 8, 20, 3,-9])

print(np.min(a))

-9


In [141]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

c = np.matmul(a, b)          # matmul() --------> used for matrix multiplication

print(c)

[[19 22]
 [43 50]]


In [ ]:
#   {  "@" ------------> also used instead of matmul() }

a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(a @ b)

In [142]:
#  np.unique()  --------->  find only the unique element in array

a = np.random.randint(1, 10, 15)



print("Original:", a)
print("Unique:", np.unique(a))

Original: [1 2 2 6 8 1 3 4 3 8 3 6 7 1 1]
Unique: [1 2 3 4 6 7 8]


In [150]:

score = []

for i in range(5):
    b = int(input())
    score.append(b)

ay = np.array(score)

print("Array =", score)
print("Sum   =", np.sum(score))
print("Mean  =", np.mean(score))
print("Std   =", np.std(score))
print("Min   =", np.min(score))
print("unique runs =", np.unique(score))

4
5
6
7
8
Array = [4, 5, 6, 7, 8]
Sum   = 30
Mean  = 6.0
Std   = 1.4142135623730951
Min   = 4
unique runs = [4 5 6 7 8]


In [155]:
#------------------ TAKING INPUTS ------------------------


scores = input().split()
print(scores)

scores = [int(x)for x in scores]
print(scores)


2 3 4 5 6
['2', '3', '4', '5', '6']
[2, 3, 4, 5, 6]
