<a href="https://colab.research.google.com/github/Sauvi72/Data_sci_Python/blob/main/Que_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:


import numpy as np

n = int(input("Number of items: "))

prices = []

for i in range(n):
    prices.append(int(input()))

prices = np.array(prices)

print("Prices =", prices)

print("Total Bill    =", np.sum(prices))
print("Average Price =", np.mean(prices))
print("Minimum Price =", np.min(prices))
print("Maximum Price =", np.max(prices))
print("Std Dev       =", np.std(prices))

print("Sorted Prices =", np.sort(prices))
print("Unique Prices =", np.unique(prices))

print("Items > 100   =", prices[np.where(prices > 100)])



Number of items: 2
3
4
Prices = [3 4]
Total Bill    = 7
Average Price = 3.5
Minimum Price = 3
Maximum Price = 4
Std Dev       = 0.5
Sorted Prices = [3 4]
Unique Prices = [3 4]
Items > 100   = []


In [12]:
#create a 5*5 matrix of random integer


n = int(input("size of rows:"))
m = int(input("size of col:"))


for i in range(n):
  for j in range(m):
    print(np.random.randint(100),end=" ")
  print()

size of rows:4
size of col:4
77 22 28 78 
39 21 63 5 
62 45 5 72 
68 9 41 22 


In [23]:
import numpy as np

n = int(input("size of rows: "))
m = int(input("size of col: "))

a = np.random.randint(-10, 10, (n, m))

sum_row = np.sum(a, axis=1)
sum_col = np.sum(a, axis=0)
ac = np.mean(a, axis=1)
ad = np.mean(a, axis=0)

z = a.copy()

for i in range(n):
    for j in range(m):
        if z[i][j] % 2 == 0:
            z[i][j] = -1

row_sorted = np.sort(a, axis=1)
col_sorted = np.sort(a, axis=0)

print("Original matrix:\n", a)
print()

for i in range(n):
    cnt_n = 0
    for j in range(m):
        if a[i][j]<0:
          cnt_n = cnt_n + 1
    print("negative columnwise : ",cnt_n)


print("Total sum of each row:", sum_row)
print("Total sum of each column:", sum_col)
print()
print("Row means:", ac)
print("Column means:", ad)
print()

print("Altered matrix:\n", z)
print()

print("Row-wise sorted matrix:\n", row_sorted)
print()

print("Column-wise sorted matrix:\n", col_sorted)
print()



size of rows: 4
size of col: 4
negative columnwise :  2
negative columnwise :  2
negative columnwise :  1
negative columnwise :  2
Original matrix:
 [[  3  -2   9 -10]
 [  2   3  -1  -6]
 [ -2   0   9   6]
 [  8  -1   5  -8]]

Total sum of each row: [ 0 -2 13  4]
Total sum of each column: [ 11   0  22 -18]

Row means: [ 0.   -0.5   3.25  1.  ]
Column means: [ 2.75  0.    5.5  -4.5 ]

Altered matrix:
 [[ 3 -1  9 -1]
 [-1  3 -1 -1]
 [-1 -1  9 -1]
 [-1 -1  5 -1]]

Row-wise sorted matrix:
 [[-10  -2   3   9]
 [ -6  -1   2   3]
 [ -2   0   6   9]
 [ -8  -1   5   8]]

Column-wise sorted matrix:
 [[ -2  -2  -1 -10]
 [  2  -1   5  -8]
 [  3   0   9  -6]
 [  8   3   9   6]]



In [30]:
import numpy as np

n = int(input("size of rows: "))
m = int(input("size of col: "))

stock = np.random.randint(0, 10, (n, m))
print("Stock Level Matrix:\n", stock)

p = int(input("size of rows: "))
q = int(input("size of col: "))

demand = np.random.randint(-10, 10, (p, q))
print("Demand Matrix:\n", demand)

if (n, m) != (p, q):
    print("Matrices must have same dimensions!")
else:
    remain = stock - demand
    print("Remaining Stock:\n", remain)


replace = np.random.randint(0, 10, (m, n))
print("Stock Level Matrix:\n", replace)

for i in range(m):
  for j in range(n):
    if replace[i][j]<0:
      replace[i][j] = 0


print("replaced values : \n" , replace)
print()

#total shortage
sum = 0
for i in range(n):
  for j in range(m):
    if remain[i][j]<0:
      sum = sum + remain[i][j]


print("total shortage: ", sum*-1)
print()


#product with zero stock
cnt_stock = 0
for i in range(n):
  for j in range(m):
    if remain[i][j]<=0:
      cnt_stock = cnt_stock + 1

print("total product with zero stock : " , cnt_stock )
print()

#sort

row_sorted = np.sort(remain, axis=1)
col_sorted = np.sort(remain, axis=0)

print("row_sorted : ",row_sorted)
print()
print("col_sorted : ", col_sorted)




size of rows: 4
size of col: 4
Stock Level Matrix:
 [[6 8 7 0]
 [9 8 5 5]
 [3 3 4 4]
 [6 7 6 6]]
size of rows: 4
size of col: 4
Demand Matrix:
 [[ 0  4  3 -9]
 [ 2  3  4  7]
 [ 3  3 -1  7]
 [-9 -8 -3 -8]]
Remaining Stock:
 [[ 6  4  4  9]
 [ 7  5  1 -2]
 [ 0  0  5 -3]
 [15 15  9 14]]
Stock Level Matrix:
 [[6 9 8 8]
 [2 6 1 1]
 [4 9 0 3]
 [3 8 7 2]]
replaced values : 
 [[6 9 8 8]
 [2 6 1 1]
 [4 9 0 3]
 [3 8 7 2]]

total shortage:  5

total product with zero stock :  2

row_sorted :  [[ 4  4  6  9]
 [-2  1  5  7]
 [-3  0  0  5]
 [ 9 14 15 15]]

col_sorted :  [[ 0  0  1 -3]
 [ 6  4  4 -2]
 [ 7  5  5  9]
 [15 15  9 14]]
